name: CI

on:
  pull_request:
    branches:
      - '**'
      - '*'
  push:
    branches:
      - '*'
      - '**'
      - '!renovate/**'
    tags:
      - '.*'

jobs:
  build:
    runs-on: ubuntu-latest

    name: CI

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - run: yarn

      - run: yarn lint
        env:
          NODE_ENV: production

      - run: yarn test

      - run: yarn build
